// Main Index File for Test Pages
// -------------------------------------------
// This file serves as the entry point for all test components in the testing environment.
// It renders an AppBar with navigation links to all available test modules, such as "Product."
// The route definitions are dynamically generated by 'scripts/generate-test-routes.js'
// The RenderRoutes component dynamically renders the corresponding module based on the selected route.

import { NavigationMenu, NavigationMenuItem, NavigationMenuLink } from '@shadcn-components/navigation-menu'
import { cn } from '@shadcn/lib/utils'
// Import the generated routes instead of defining them here
import GENERATED_ROUTE_DEFINITIONS from '@tests/pages/generated_routes'
import RenderRoutes from '@tests/pages/RenderRoutes'
import withDynamicRoutes from '@tests/shared/hoc/withDynamicRoutes'
import { Link } from 'react-router-dom'

// Remove the hardcoded ROUTE_DEFINITIONS array

function Tests({ routes }) {
  return (
    <>
      <header className="border-b">
        <div className="container mx-auto px-4">
          <NavigationMenu className="py-4">
            {routes.map(({ path, label }) => (
              <NavigationMenuItem key={path}>
                <NavigationMenuLink
                  asChild
                  className={cn(
                    "text-sm font-medium transition-colors hover:text-primary",
                    "text-muted-foreground"
                  )}
                >
                  <Link to={path}>
                    {label}
                  </Link>
                </NavigationMenuLink>
              </NavigationMenuItem>
            ))}
          </NavigationMenu>
        </div>
      </header>
      <main className="container mx-auto px-4 py-6">
        <RenderRoutes routes={routes} noBack />
      </main>
    </>
  )
}

// Pass the imported generated definitions to the HOC
export default withDynamicRoutes(GENERATED_ROUTE_DEFINITIONS)(Tests)
